### ISSUE TITLE
Alignment  working in respect to text, not slide

### ISSUE THREAD

**Issue by jpssrocha** [manjavacas/typslides#1]
Hi,

 i'm using typslides 1.2.0, with typst 0.12.0.  And a funny thing is happening ...

When i use the align function from typst within a frame, it aligns what is inside the align call with the largest line of text that came before it.

For example, this snippet:

```typst
#slide(title: "Coletando os dados")[

  - #stress[KPCA + SVM Linear]  - $mu = 93.81%$, $sigma = 1.3%$
  - #stress[PCA + Kernel SVM] - $mu = 95.58%$, $sigma = 1.2%$
  - #stress[Tamanho do efeito] - $mu_b - mu_a = 1.77%$

  #align(center)[ 
   #image("figures/kde2.svg", height: 65%)
  ]
]
```

Renders this:

![image](https://github.com/user-attachments/assets/8001ee3d-d2a8-44ff-b2e7-c2c6297ad8b6)

But if i put a long text at the top with `#lorem` for example, (or anywhere in the slide)  it becomes this:

![image](https://github.com/user-attachments/assets/5f4a12a7-1639-4207-8982-635c3abff5fa)

Was trying to figure out whats happening but i don't know a lot of typst yet ...

PS: Thanks for sharing this awesome template, i like how it's minimal and clean, just did a presentation using it!

**Comment by manjavacas** [comment]
Hi @jpssrocha! First of all, thank you for using _Typslides_ 😃 

Indeed, this did not happen in the previous version of _Typslides_ and it is a bug that I am currently fixing.

I think it is related to the content of the slides being wrapped inside a `block` and that forces that alignment.

Going to try to fix it in the next few days, along with other bugs I've found, and I hope to have it ready for next week.

Best regards and thanks for your report 👍🏻

**Comment by manjavacas** [comment]
Hi again, @jpssrocha. I think I managed to solve the bug.

Here is the new release. I will try to make it published asap: https://github.com/manjavacas/typslides/releases/tag/v1.2.1

Thanks again, and feel free to open more issues for further inquiries 👍🏻

**Comment by jpssrocha** [comment]
Thanks @manjavacas !!
